highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Ngoc Hoang's Resume
name: Ngoc Hoang
email: hoangthimyngoc@hotmail.com
email_full: mailto:hoangthimyngoc@hotmail.com
website: github.io/htmn88
website_full: https://jekyller.github.io/sustain
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Mariankatu 24C 18
  postcode: 00170 
  city: Helsinki
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
